import Head from "next/head";
import { FC } from "react";

export const MetaData: FC = () => {
  return (
    <Head>
      <title>Next App</title>
      <meta name="description" content="Generated by betich's boilerplate Next.js template" />
    </Head>
  );
};
